## Project specific config ###
language: generic

sudo: false

# os:
# - linux
# - osx

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

#branches:
#  only:
#  - master

services:
- docker

addons:
  apt:
    packages:
    - git

script:
- chmod u+x build-package.sh
- ./build-package.sh

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: builds/synergy-*-Linux-x86_64.*
    skip_cleanup: true
    file_glob: true
    on:
      tags: true
